### PR TITLE
fix:usr: Show useful error when failing to open epic

### PR DESCRIPTION
**Pull request by j-martin**
... or iteration.

### CODE REVIEW

**Comment by andjosh** [comment]
Published in v2.6.1

**Comment by j-martin** [comment]
@andjosh I think the commit did not make it in for some reason. I am looking at 2.6.1 and I am not seeing the guards:

```club-story.js
// club-story.js L293
                                    if (program.open)
                                        openURL(stories_1.default.storyURL(story));
                                    if (program.openEpic)
                                        openURL(stories_1.default.buildURL('epic', story.epic_id));
                                    if (program.openIteration)
                                        openURL(stories_1.default.buildURL('iteration', story.iteration_id));
                                    if (program.openProject)
                                        openURL(stories_1.default.buildURL('project', story.project_id));

```

**Comment by andjosh** [comment]
Huh... I'll try tagging it again!

**Comment by andjosh** [comment]
Republished in v2.6.2

**Comment by j-martin** [comment]
I hate to tell you this but 2.6.2 has no build directory... :\

**Comment by andjosh** [comment]
😅 okay - published in 2.6.3

**Comment by andjosh** [comment]
Note to self: the `/build` is currently in the `.gitignore` but is not _built_ during npm publishing of the module. So we currently need to run `npm run build` _before_ `npm publish`....

**Comment by j-martin** [comment]
I can confirm it worked and the code works as expected. :)

**Pull request merged**
