### PR TITLE
Convert to typescript

### PR DESCRIPTION
**Pull request by j-martin**
Depends on https://github.com/clubhouse/clubhouse-lib/pull/34
Closes https://github.com/andjosh/clubhouse-cli/issues/66

There is more change I want to make, but let's keep things simple for now.

Note that the strict mode is not enabled. Errors will be fixed later on.

### CODE REVIEW

**Comment by andjosh** [comment]
Thanks for this! LGTM as long as https://github.com/clubhouse/clubhouse-lib/pull/34 gets merged in - I'll wait for that.

**Comment by j-martin** [comment]
@andjosh it's ready to be merged.

**Comment by j-martin** [comment]
@andjosh it's not ready. The offending line was https://github.com/andjosh/clubhouse-cli/compare/afb1ec9a97f1979397a5deb815e8e105243d6983..49d0a037bf671fe02e02e8003d740b56e38a84d4#diff-3ab5a6ab8fc9b172db48dd64f1586cb4L19 (and the fact I had the lib there locally).

**Comment by j-martin** [comment]
I meant it is now ready to be reviewed/merged.

**Comment by andjosh** [comment]
Thanks for working on this @j-martin !

**Pull request merged**
