### PR TITLE
Refactor CircleCI into a matrix

### PR DESCRIPTION
**Pull request by charpeni**
- Simplified the CircleCI configuration so it's easier to test against multiple versions with a matrix.
- Added tests against Node 16 (soon to be LTS).

### CODE REVIEW

**Comment by j-martin** [comment]
Hi @charpeni can you add your change to the [changelog](https://github.com/andjosh/clubhouse-cli/blob/master/CHANGELOG.md)? Your PR description is totally fine for that.

**Review by j-martin — APPROVED** [review]
For some reason the passed checks are not visible here, but the Circle change are successful.

https://app.circleci.com/pipelines/github/charpeni/clubhouse-cli/5/workflows/0bc267a5-4452-439f-9be9-4c6bb3073653/jobs/28

**Comment by j-martin** [comment]
Merci bien!

**Comment by charpeni** [comment]
Ça fait plaisir!

**Pull request merged**
